import './globals.css'

export const metadata = {
  title: 'Pgm-Search',
  description: 'App like Google generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
