import { SearchHeader } from '@/components'
import '@/app/globals.css'

export const metadata = {
  title: 'Pgm-Search',
  description: 'App like Google generated by create next app',
}

export default function SearchLayout({ children }) {
  return (
    <div>
        <SearchHeader />
        {children}
    </div>
  )
}